Logging 1
Otus-DevOps-2021-11/Arthur0404_microservices pull request #5
Opened 2022-04-09 06:13 UTC by Arthur0404

# Выполнено ДЗ №

 - [ ] Основное ДЗ
 - [ ] Задание со *

## В процессе сделано:
 - Пункт 1
 - Пункт 2

## Как запустить проект:
 - Например, запустить команду X в директории Y

## Как проверить работоспособность:
 - Например, перейти по ссылке http://localhost:8080

## PR checklist
 - [ ] Выставил label с номером домашнего задания
 - [ ] Выставил label с темой домашнего задания

2022-04-09 06:14 UTC, Arthur0404 commented
Сделано домашнее задание по логированию

2022-04-11 07:30 UTC, mrgreyves requested changes
Здравствуйте!)
Оставил комментарий к файлу с тестами
Надо бы их вернуть
ДЗ возвращаю на доработку

2022-04-11 07:30 UTC, mrgreyves commented on .github/workflows/run_tests.yml
> -name: Run tests for OTUS homework
Эммм, а зачем закомментили тесты то?0_о

2022-04-11 16:54 UTC, Arthur0404 commented
Вернул тесты - не пойму почему не проходят они?

2022-04-11 16:56 UTC, Arthur0404 commented on .github/workflows/run_tests.yml
> -name: Run tests for OTUS homework
не пойму почему не проходят тесты - вроде все написано правильно

2022-04-11 19:03 UTC, Arthur0404 commented on .github/workflows/run_tests.yml
> -name: Run tests for OTUS homework
проверил много раз - написано правильно но тесты валятся

2022-04-13 08:38 UTC, mrgreyves approved these changes
Здравствуйте!)
Во время тестов не запускается часть компонентов приложения, я могу принять дз, но имейте ввиду что в дальнейшем могут быть проблемы

2022-04-13 16:53 UTC, merged